// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/container/list": {
            "get": {
                "description": "获取我的容器列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "container"
                ],
                "summary": "获取我的容器列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page no",
                        "name": "page_no",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/image/list": {
            "get": {
                "description": "获取镜像列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "获取镜像列表",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ImageList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "就是用户登录呗",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录输入",
                        "name": "struct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserLoginOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/resource/cpu": {
            "get": {
                "description": "获取CPU基本的状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "获取CPU基本的状态",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/resource/gpu": {
            "get": {
                "description": "获取GPU基本的状态包含个数、占用率等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resource"
                ],
                "summary": "获取GPU基本的状态",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GPUList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "description": "用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page no",
                        "name": "page_no",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "get": {
                "description": "就是用户登出呗",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册（仅限管理员）",
                "parameters": [
                    {
                        "description": "新建用户输入",
                        "name": "struct",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NewUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.GPUList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "cuda_driver_version": {
                    "type": "string"
                },
                "driver_version": {
                    "type": "string"
                },
                "gpu_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GPUStatus"
                    }
                }
            }
        },
        "dto.GPUStatus": {
            "type": "object",
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "memory_total": {
                    "type": "integer"
                },
                "memory_used": {
                    "type": "integer"
                },
                "power_default_limit": {
                    "type": "integer"
                },
                "power_usage": {
                    "type": "integer"
                },
                "process_info": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ProcessInfoCombined"
                    }
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "dto.ImageInfo": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                }
            }
        },
        "dto.ImageList": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ImageInfo"
                    }
                }
            }
        },
        "dto.NewUserInput": {
            "type": "object",
            "required": [
                "email",
                "raw_password",
                "user_role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "raw_password": {
                    "type": "string"
                },
                "user_role": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.ProcessInfoCombined": {
            "type": "object",
            "properties": {
                "command_line": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "used_gpu_memory": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "dto.UserLoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "管理员密码",
                    "type": "string",
                    "example": "12345678"
                },
                "username": {
                    "description": "管理员用户名",
                    "type": "string",
                    "example": "joexu01"
                }
            }
        },
        "dto.UserLoginOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "返回的Token",
                    "type": "string",
                    "example": "token"
                }
            }
        },
        "middleware.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "err_msg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {},
                "trace_id": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
