definitions:
  dto.GPUList:
    properties:
      count:
        type: integer
      cuda_driver_version:
        type: string
      driver_version:
        type: string
      gpu_info:
        items:
          $ref: '#/definitions/dto.GPUStatus'
        type: array
    type: object
  dto.GPUStatus:
    properties:
      device_name:
        type: string
      memory_total:
        type: integer
      memory_used:
        type: integer
      power_default_limit:
        type: integer
      power_usage:
        type: integer
      process_info:
        items:
          $ref: '#/definitions/dto.ProcessInfoCombined'
        type: array
      uuid:
        type: string
    type: object
  dto.ImageInfo:
    properties:
      created:
        type: string
      image_id:
        type: string
      repository:
        type: string
      size:
        type: string
    type: object
  dto.ImageList:
    properties:
      list:
        items:
          $ref: '#/definitions/dto.ImageInfo'
        type: array
    type: object
  dto.NewUserInput:
    properties:
      email:
        type: string
      raw_password:
        type: string
      user_role:
        type: integer
      username:
        type: string
    required:
    - email
    - raw_password
    - user_role
    - username
    type: object
  dto.ProcessInfoCombined:
    properties:
      command_line:
        type: string
      pid:
        type: integer
      used_gpu_memory:
        type: integer
      user:
        type: string
    type: object
  dto.UserContainerInfo:
    properties:
      command:
        type: string
      container_id:
        type: string
      created:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      ports:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  dto.UserLoginInput:
    properties:
      password:
        description: 管理员密码
        example: "12345678"
        type: string
      username:
        description: 管理员用户名
        example: joexu01
        type: string
    required:
    - password
    - username
    type: object
  dto.UserLoginOutput:
    properties:
      token:
        description: 返回的Token
        example: token
        type: string
    type: object
  middleware.Response:
    properties:
      data: {}
      err_msg:
        type: string
      errno:
        type: integer
      stack: {}
      trace_id: {}
    type: object
info:
  contact: {}
paths:
  /container/list:
    get:
      description: 获取我的容器列表
      parameters:
      - description: page size
        in: query
        name: page_size
        type: integer
      - description: page no
        in: query
        name: page_no
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserContainerInfo'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 获取我的容器列表
      tags:
      - container
  /image/list:
    get:
      description: 获取镜像列表
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ImageList'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 获取镜像列表
      tags:
      - image
  /login:
    post:
      consumes:
      - application/json
      description: 就是用户登录呗
      parameters:
      - description: 用户登录输入
        in: body
        name: struct
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.UserLoginOutput'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 用户登录
      tags:
      - user
  /resource/cpu:
    get:
      description: 获取CPU基本的状态
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 获取CPU基本的状态
      tags:
      - resource
  /resource/gpu:
    get:
      description: 获取GPU基本的状态包含个数、占用率等
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/middleware.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.GPUList'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 获取GPU基本的状态
      tags:
      - resource
  /user/list:
    get:
      description: 用户列表
      parameters:
      - description: page size
        in: query
        name: page_size
        type: integer
      - description: page no
        in: query
        name: page_no
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 用户列表
      tags:
      - user
  /user/logout:
    get:
      consumes:
      - application/json
      description: 就是用户登出呗
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/middleware.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 用户登出
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 新建用户输入
        in: body
        name: struct
        required: true
        schema:
          $ref: '#/definitions/dto.NewUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/middleware.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 用户注册（仅限管理员）
      tags:
      - user
swagger: "2.0"
